name: Sync Privacy Policy to Gist

on:
  push:
    branches: [main]
    paths: [privacy-policy.md]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update gist
        uses: popsiclestick/gist-sync-action@v1.2.0
        with:
          auth: ${{ secrets.GIST_PAT }}
          gist_url: https://gist.github.com/LuDraGa/782b874f1e7fe0076fb2bf1509937e95
          gist_title: privacy-policy.md
          github_file: privacy-policy.md
